Parameters:
  LaunchTemplateName:
    Type: String
    Default: app-template
    Description: Enter a application server's launch template name.
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  ImageId:
    Type: AWS::EC2::Image::Id
  SecurityGroupWeb:
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroupApp:
    Type: AWS::EC2::SecurityGroup::Id
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetWeb:
    Type: List<AWS::EC2::Subnet::Id>
  SubnetApp:
    Type: List<AWS::EC2::Subnet::Id>
Resources:
